development:
  environment: "sandbox"
  username: "seller_1356374325_biz_api1.novationmobile.com"
  password: "1356374345"
  signature: "A3nhyYdJ.1KKuvMSCddnwJvnVdAWADtFSv31ZxzBbzThtckGXTxhl4Fv"
  application_id: "APP-80W284485P519543T"
  api_cert_file:

test:
  environment: "sandbox"
  username: "seller_1356374325_biz_api1.novationmobile.com"
  password: "1356374345"
  signature: "A3nhyYdJ.1KKuvMSCddnwJvnVdAWADtFSv31ZxzBbzThtckGXTxhl4Fv"
  application_id: "APP-80W284485P519543T"
  api_cert_file: "/path/to_cert"

production:
  environment: "production"
  username: "my_production_username"
  password: "my_production_password"
  signature: "my_production_signature"
  application_id: "my_production_app_id"
  api_cert_file: "/path/to_cert"