--- 
Arts & Entertainment: ae
Arcade: ae
Art Gallery: ae
Bowling Alley: ae
Casino: ae
Comedy Club: ae
General Entertainment: ae
Historic Site: ae
Movie Theater: ae
Indie Movie Theater: ae
Multiplex: ae
Museum: ae
Art Museum: ae
History Museum: ae
Planetarium: ae
Science Museum: ae
Music Venue: food
Concert Hall: food
Jazz Club: food
Piano Bar: food
Rock Club: food
Performing Arts Venue: ae
Dance Studio: ae
Indie or Off Broadway Theater: ae
Opera House: ae
Theater: ae
Pool Hall: ae
Racetrack: ae
Stadium: ae
Baseball Stadium: ae
Basketball Stadium: ae
Cricket Ground: ae
Football Stadium: ae
Hockey Stadium: ae
Soccer Stadium: ae
Tennis: ae
Track: ae
Strip Club: food
Theme Park: ae
Water Park: ae
Zoo or Aquarium: ae
College & University: ae
College Academic Building: ae
College Arts Building: ae
College Communications Building: ae
College Engineering Building: ae
College History Building: ae
College Math Building: ae
College Science Building: ae
College Technology Building: ae
College Administrative Building: ae
College Auditorium: ae
College Bookstore: ae
College Cafeteria: food
College Classroom: ae
College Dorm: ae
College Gym: ae
College Lab: ae
College Library: ae
College Quad: ae
College Rec Center: ae
College Stadium: sport
College Baseball Diamond: sport
College Basketball Court: sport
College Cricket Pitch: sport
College Football Field: sport
College Hockey Rink: sport
College Soccer Field: sport
College Tennis Court: sport
College Track: sport
College Theater: ae
Community College: ae
Fraternity House: ae
General College & University: ae
Law School: ae
Medical School: ae
Sorority House: ae
Student Center: ae
Trade School: ae
University: ae
Food: food
African Restaurant: food
American Restaurant: food
Arepa Restaurant: food
Argentinian Restaurant: food
Asian Restaurant: food
Australian Restaurant: food
BBQ Joint: food
Bagel Shop: food
Bakery: food
Brazilian Restaurant: food
Breakfast Spot: food
Brewery: food
Burger Joint: food
Burrito Place: food
"Caf\xC3\xA9": food
Cajun or Creole Restaurant: food
Caribbean Restaurant: food
Chinese Restaurant: food
Coffee Shop: food
Cuban Restaurant: food
Cupcake Shop: food
Deli or Bodega: food
Dessert Shop: food
Dim Sum Restaurant: food
Diner: food
Distillery: food
Donut Shop: food
Dumpling Restaurant: food
Eastern European Restaurant: food
Ethiopian Restaurant: food
Falafel Restaurant: food
Fast Food Restaurant: food
Filipino Restaurant: food
Fish & Chips Shop: food
Food Court: food
Food Truck: food
French Restaurant: food
Fried Chicken Joint: food
Gastropub: food
German Restaurant: food
Gluten-free Restaurant: food
Greek Restaurant: food
Hot Dog Joint: food
Ice Cream Shop: food
Indian Restaurant: food
Indonesian Restaurant: food
Italian Restaurant: food
Japanese Restaurant: food
Juice Bar: food
Korean Restaurant: food
Latin American Restaurant: food
Mac & Cheese Joint: food
Malaysian Restaurant: food
Mediterranean Restaurant: food
Mexican Restaurant: food
Middle Eastern Restaurant: food
Molecular Gastronomy Restaurant: food
Mongolian Restaurant: food
Moroccan Restaurant: food
New American Restaurant: food
Peruvian Restaurant: food
Pizza Place: food
Portuguese Restaurant: food
Ramen or Noodle House: food
Restaurant: food
Salad Place: food
Sandwich Place: food
Scandinavian Restaurant: food
Seafood Restaurant: food
Snack Place: food
Soup Place: food
South American Restaurant: food
Southern or Soul Food Restaurant: food
Spanish Restaurant: food
Paella Restaurant: food
Steakhouse: food
Sushi Restaurant: food
Swiss Restaurant: food
Taco Place: food
Tapas Restaurant: food
Tea Room: food
Thai Restaurant: food
Vegetarian or Vegan Restaurant: food
Vietnamese Restaurant: food
Winery: food
Wings Joint: food
Great Outdoors: sport
Baseball Field: sport
Basketball Court: sport
Beach: sport
Surf Spot: sport
Bridge: sport
Campground: sport
Cemetery: sport
Dog Run: sport
Farm: sport
Field: sport
Garden Center: home
Garden: sport
Golf Course: sport
Harbor or Marina: sport
Hiking Trail: sport
Hot Spring: sport
Lake: sport
Lighthouse: sport
Mountain: sport
Other Great Outdoors: sport
Park: sport
Playground: sport
Plaza: sport
Pool: sport
River: sport
Scenic Lookout: sport
Sculpture Garden: ae
Skate Park: sport
Skating Rink: sport
Ski Area: sport
Apres Ski Bar: sport
Ski Chairlift: sport
Ski Chalet: sport
Ski Lodge: sport
Ski Trail: sport
Soccer Field: sport
Stable: sport
Tennis Court: sport
Vineyard: food
Volleyball Court: sport
Nightlife Spot: food
Bar: food
Beer Garden: food
Cocktail Bar: food
Dive Bar: food
Gay Bar: food
Hookah Bar: food
Hotel Bar: food
Karaoke Bar: food
Lounge: food
Nightclub: food
Other Nightlife: food
Pub: food
Sake Bar: food
Speakeasy: food
Sports Bar: food
Whisky Bar: food
Wine Bar: food
Professional & Other Places: home
Animal Shelter: pet
Apartment Building / Condo Complex: home
Building: home
Convention Center: home
Meeting Room: home
Event Space: home
Factory: home
Fair: home
Government Building: home
Capitol Building: home
City Hall: home
Courthouse: home
Fire Station: home
Monument or Landmark: home
Police Station: home
Library: home
Medical Center: home
Dentist's Office: home
Doctor's Office: home
Emergency Room: home
Hospital: home
Optical Shop: home
Veterinarian: home
Military Base: home
Office: home
Auditorium: home
Cafeteria: home
Conference Room: home
Coworking Space: home
Tech Startup: home
Parking: home
Post Office: home
Religious Center: home
Church: home
Mosque: home
Shrine: home
Synagogue: home
Temple: home
School: home
High School: home
Voting Booth: home
Antique Shop: home
Arts & Crafts Store: home
Automotive Shop: car
Bike Shop: sport
Board Shop: sport
Bookstore: ae
Bridal Shop: fashion
Camera Store: tech
Candy Store: food
Clothing Store: fashion
Accessories Store: fashion
Boutique: fashion
Kids Store: fashion
Lingerie Store: fashion
Men's Store: fashion
Shoe Store: fashion
Women's Store: fashion
Convenience Store: home
Cosmetics Shop: beauty
Department Store: fashion
Drugstore or Pharmacy: home
Electronics Store: tech
Flea Market: home
Flower Shop: home
Furniture or Home Store: home
Gift Shop: home
Yoga Studio: sport
Hardware Store: home
Hobby Shop: ae
Internet Cafe: ae
Jewelry Store: fashion
Laundromat or Dry Cleaner: home
Mall: fashion
Music Store: ae
Record Shop: ae
Salon or Barbershop: beauty
Smoke Shop: home
Spa or Massage: beauty
Sporting Goods Shop: sport
Tanning Salon: beauty
Tattoo Parlor: beauty
Thrift or Vintage Store: fashion
Toy or Game Store: ae
Video Game Store: ae
Video Store: ae
