--- 
Arts & Entertainment: ae
Arcade: ae
Art Gallery: ae
Bowling Alley: ae
Casino: ae
Comedy Club: ae
General Entertainment: ae
Historic Site: ae
Movie Theater: ae
Indie Movie Theater: ae
Multiplex: ae
Museum: ae
Art Museum: ae
History Museum: ae
Planetarium: ae
Science Museum: ae
Music Venue: bar
Concert Hall: bar
Jazz Club: bar
Piano Bar: bar
Rock Club: bar
Performing Arts Venue: ae
Dance Studio: ae
Indie or Off Broadway Theater: ae
Opera House: ae
Theater: ae
Pool Hall: ae
Racetrack: ae
Stadium: ae
Baseball Stadium: ae
Basketball Stadium: ae
Cricket Ground: ae
Football Stadium: ae
Hockey Stadium: ae
Soccer Stadium: ae
Tennis: ae
Track: ae
Strip Club: bar
Theme Park: ae
Water Park: ae
Zoo or Aquarium: ae
Food: food
African Restaurant: food
American Restaurant: food
Arepa Restaurant: food
Argentinian Restaurant: food
Asian Restaurant: food
Australian Restaurant: food
BBQ Joint: food
Bagel Shop: food
Bakery: food
Brazilian Restaurant: food
Breakfast Spot: food
Brewery: bar
Burger Joint: food
Burrito Place: food
"Caf\xC3\xA9": food
Cajun or Creole Restaurant: food
Caribbean Restaurant: food
Chinese Restaurant: food
Coffee Shop: food
Cuban Restaurant: food
Cupcake Shop: food
Deli or Bodega: food
Dessert Shop: food
Dim Sum Restaurant: food
Diner: food
Distillery: food
Donut Shop: food
Dumpling Restaurant: food
Eastern European Restaurant: food
Ethiopian Restaurant: food
Falafel Restaurant: food
Fast Food Restaurant: food
Filipino Restaurants: food
Food Court: food
Food Truck: food
French Restaurant: food
Fried Chicken Joint: food
Gastropub: food
German Restaurant: food
Gluten-free Restaurant: food
Greek Restaurant: food
Hot Dog Joint: food
Ice Cream Shop: food
Indian Restaurant: food
Indonesian Restaurant: food
Italian Restaurant: food
Japanese Restaurant: food
Juice Bar: food
Korean Restaurant: food
Latin American Restaurant: food
Mac & Cheese Joint: food
Malaysian Restaurant: food
Mediterranean Restaurant: food
Mexican Restaurant: food
Middle Eastern Restaurant: food
Molecular Gastronomy Restaurant: food
Mongolian Restaurants: food
Moroccan Restaurant: food
New American Restaurant: food
Peruvian Restaurants: food
Pizza Place: food
Portuguese Restaurant: food
Ramen or Noodle House: food
Restaurant: food
Salad Place: food
Sandwich Place: food
Scandinavian Restaurant: food
Seafood Restaurant: food
Snack Place: food
Soup Place: food
South American Restaurant: food
Southern or Soul Food Restaurant: food
Spanish Restaurant: food
Paella Restaurant: food
Steakhouse: food
Sushi Restaurant: food
Swiss Restaurant: food
Taco Place: food
Tapas Restaurant: food
Tea Room: food
Thai Restaurant: food
Vegetarian or Vegan Restaurant: food
Vietnamese Restaurant: food
Winery: food
Wings Joint: food
Nightlife Spot: bar
Bar: bar
Beer Garden: bar
Cocktail Bar: bar
Dive Bar: bar
Gay Bar: bar
Hookah Bar: bar
Hotel Bar: bar
Karaoke Bar: bar
Lounge: bar
Nightclub: bar
Other Nightlife: bar
Pub: bar
Sake Bar: bar
Speakeasy: bar
Sports Bar: bar
Whisky Bar: bar
Wine Bar: bar
Animal Shelter: pet
Antique Shop: home
Arts & Crafts Store: home
Automotive Shop: car
Bike Shop: sport
Board Shop: sport
Bookstore: ae
Bridal Shop: fashion
Candy Store: food
Clothing Store: fashion
Accessories Store: fashion
Boutique: fashion
Kids Store: fashion
Lingerie Store: fashion
Men's Store: fashion
Shoe Store: fashion
Women's Store: fashion
Convenience Store: home
Cosmetics Shop: beauty
Department Store: fashion
Drugstore or Pharmacy: home
Electronics Store: tech
Flea Market: home
Flower Shop: home
Furniture or Home Store: home
Gift Shop: home
Yoga Studio: sport
Hardware Store: home
Hobby Shop: ae
Internet Cafe: ae
Jewelry Store: fashion
Laundromat or Dry Cleaner: home
Mall: fashion
Music Store: ae
Record Shop: ae
Salon or Barbershop: beauty
Smoke Shop: ae
Spa or Massage: beauty
Sporting Goods Shop: sport
Tanning Salon: beauty
Tattoo Parlor: beauty
Thrift or Vintage Store: fashion
Toy or Game Store: ae
Video Game Store: ae
Video Store: ae
