test:
  address: ec2-23-22-6-59.compute-1.amazonaws.com
  port: 9352

development:
  bin_path: '/usr/local/bin'
  searchd_binary_name: 'searchd'
  indexer_binary_name: 'indexer'

staging:
  version: 1.10-beta
  min_prefix_len: 3

production:
  version: 1.10-beta
  min_prefix_len: 3
